on:
  workflow_dispatch:


env:
  terraform_version: 1.12.2
  terraform_wrapper: false
  terraform_output_file: tfplan

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout


jobs:
  destroy:
    runs-on: ubuntu-latest
    # This job requires approval to run
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.terraform_version }}
          terraform_wrapper: ${{ env.terraform_wrapper }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        id: destroy
        if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
        run: |
          terraform plan -destroy -out=${{ env.terraform_output_file }} -input=false
          terraform apply -auto-approve -input=false ${{ env.terraform_output_file }}