name: 'Terraform Apply'

on:
  workflow_dispatch:
  push:
    branches:
      - main 

env:
  terraform_version: 1.12.2
  terraform_wrapper: false
  terraform_output_file: tfplan

permissions:
  id-token: write      # Required for requesting the JWT
  contents: read       # Required for checkout
  actions: read        # Required for downloading artifacts from the same run

jobs:
  plan:
    name: 'Run Terraform Validate and Plan'
    uses: ./.github/workflows/terraform-plan.yaml
    secrets: inherit

  apply:
    name: 'Apply Terraform Plan'
    runs-on: ubuntu-latest
    needs: [plan]

    # Only run if the plan job was successful
    if: needs.plan.outputs.plan-outcome == 'success'

    # Use an environment with a required reviewer for a manual approval gate
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.terraform_version }}
          terraform_wrapper: ${{ env.terraform_wrapper }}

      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan # Must match the artifact name in the reusable workflow

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        id: apply
        run: terraform apply -input=false ${{ env.terraform_output_file }} -auto-approve