# This is a reusable workflow. It cannot be run on its own.
# It is designed to be called by another workflow.
name: 'Reusable TF Plan'

on:
  workflow_call:
    inputs:
      terraform-version:
        description: 'The version of Terraform to use'
        required: false
        type: string
        default: '1.12.2'
      terraform-wrapper:
        description: 'Whether to use the Terraform wrapper'
        required: false
        type: boolean
        default: false
      output-file:
        description: 'The file to write the Terraform plan output to'
        required: false
        type: string
        default: 'tfplan'
    
    outputs:
      plan-outcome:
        description: "The outcome of the terraform plan step (success, failure)"
        value: ${{ jobs.plan.outputs.plan-outcome }}
      plan-output:
        description: "The text output of the terraform plan"
        value: ${{ jobs.plan.outputs.plan-text }}
      fmt-outcome:
        description: "The outcome of the terraform fmt step"
        value: ${{ jobs.plan.outputs.fmt-outcome }}
      init-outcome:
        description: "The outcome of the terraform init step"
        value: ${{ jobs.plan.outputs.init-outcome }}
        
permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  plan:
    name: 'Validate and Plan'
    runs-on: ubuntu-latest
    outputs:
      plan-outcome: ${{ steps.plan.outcome }}
      plan-text: ${{ steps.create-plan-output.outputs.plan }}
      fmt-outcome: ${{ steps.fmt.outcome }}
      init-outcome: ${{ steps.init.outcome }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform-version }}
          terraform_wrapper: ${{ inputs.terraform-wrapper }}

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          # Run terraform plan and capture output
          terraform plan -no-color -input=false -out=${{ inputs.output-file }} 2>&1 | tee plan_raw_output.txt
          exit ${PIPESTATUS[0]}
        continue-on-error: true
      
      - name: Create Plan Output
        id: create-plan-output
        if: always() && (steps.plan.outcome == 'success' || steps.plan.outcome == 'failure')
        run: |
          # Capture the plan output and handle multiline properly
          if [ "${{ steps.plan.outcome }}" = "success" ] && [ -f "${{ inputs.output-file }}" ]; then
            echo "Using terraform show output from plan file..."
            terraform show -no-color ${{ inputs.output-file }} > plan_output.txt
          elif [ -f "plan_raw_output.txt" ]; then
            echo "Using raw plan output from failed plan..."
            cat plan_raw_output.txt > plan_output.txt
          else
            echo "No plan output available. Plan may have failed completely." > plan_output.txt
          fi
          
          # Create a random delimiter for multiline output
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          
          # Set the output using the heredoc syntax
          echo "plan<<$EOF" >> "$GITHUB_OUTPUT"
          cat plan_output.txt >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"

      - name: Upload Terraform Plan Artifact
        if: steps.plan.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ${{ inputs.output-file }}
          retention-days: 1 # Keep artifact for one day